### ISSUE TITLE
Performous should not list broken songs

### ISSUE THREAD

**Issue by TobiX** [performous/performous#127]
If a song is incomplete (missing MP3), it should be reported as broken and not be shown in the song browser.

**Comment by nieknooijens** [comment]
I'm actually against that, because I have a database of 2000+ songs and there's no way of knowing if a song's broken if it doesn't show up in the list!! in that case it's as if the song doesn't exist, but it does take space on my hard drive.
it's only ok if there's a way to list these broken songs so I can fix them. currently I do that by writing the song down as soon as a broken song is triggered. the program doesn't crash anyway so why hide them?

**Comment by tapio** [comment]
Another complication is that IIRC for speed reasons we only parse the header of certain formats, which means we don't necessarily know if the song is broken until we start it and full note parsing is performed.

**Comment by nieknooijens** [comment]
@tapio that's probably what messes up my songmerge branch...

**Comment by Baklap4** [comment]
I Have a program which checks if there's an mp3 or txt file in the folder.
It also check if the mp3 name in the tag is equal to the physical mp3 file in the current folder.
If there are some errors it'll output them to a file so you can fix it by hand if it cannot be done programmatically. Shall i upload this program after i've refactored it?

**Comment by TobiX** [comment]
@Baklap4: Most of that code is already in Performous, e.g. it already reports some errors in the infolog.txt and on the console. Just not all errors, mainly because of performance...

**Comment by Baklap4** [comment]
Good old thread. I'm for not listing the song within the songbrowser. We have since playlist times got into performous a potential filenotfound exception being thrown. Since performous list the song you can actually add it to the playlist which creates this segfault. Calculation of duration has the need of an mp3 file.

I'm proposing the following:
Log the broken song
Forget about the song for the rest of the program.
Create an option within the webserver to view a report about 'issues' related to songs. With issues i mean basicly everything which is spewed to the console upon loading:
- MP3 Not found
- File for background,video,cover not found but found alternative
    - No files found at all
- Encoding issues with the specific text file

This way the faulty songs have a way of being listed while not being active in the current game since you cannot choose a broken song. How does this sound? @TobiX @nieknooijens

**Comment by Lord-Kamina** [comment]
I think they should be shown but with a strong visual cue as to them being broken; and of course taking into account the need to prevent the segfault currently happening.

OTOH, I believe that would require a lot more work and perhaps @Baklap4's approach is a good middle-ground.

**Comment by Baklap4** [comment]
as of now we still don't have a fix for this.
TODO
- [ ] Detected issues should be shown within the webbrowser
- [ ] Show a strong visual cue to songs in the song browser to show they're broken.

**Comment by Baklap4** [comment]
Added `Bug` label since we can get a `file not found` error upon checking the length of an MP3
