### ISSUE TITLE
Interface with Mixxx DJ Software 

### ISSUE THREAD

**Issue by daschuer** [performous/performous#140]
It would be great if Performous could be used seamlessly during a dance party using the free Mixxx DJ software. https://github.com/mixxxdj/mixxx/

The current solution is to install Performous on a second hardware and use a hardware cable to mix the Performous sound in. 
What could be the first steps to improve this? 
Both apps are using Portaudio. 

Is it possible to start a track in Performous by remote?

**Comment by nieknooijens** [comment]
hi there!

it is possible to enqueue a track remotely using the webserver-branch (not start, enqueue) but I don't think it's a good idea to tie 2 programs together, It would probably be better to add ultrastar-txt support to mixxx since performous is build as karaoke platform and not as dj-ing interface.

instead of using 2 computers you could use an audio mixer and an extra USB-soundcard to accomplish the same (you can tell mixx to use a different sound card than performous and in performous you can tell it to use a specific sound card circumventing the default linux settings). I use a xenyx 2442 for that since I need to mix in the sound of the microphones too.

**Comment by daschuer** [comment]
Thank you for the quick responds. 

Yes the sound card solution will also work, but we still need to plug the mics for the Karaoke. We may use Jack. to get around it, but the Jack implementation offered by Portaudio is not suitable for such inter process routing. 

 > add ultrastar-txt support to mixxx

Yes, this probably suits best for my case. But I am afraid it is hard to do from the scratch and to maintain this piece of code later. 

Will it possible to extract a lets say "libperformous" from your code base and reuse it in Mixxx? If Mixxx can provides somehow the track path, the seek position and the tempo, can this library then do the video rendering?

**Comment by nieknooijens** [comment]
performous is distrubuted under the same licence as mixxx (GPL)
as long as you comply with the GPL (mention all the authors and publish the
source code) you are allowed to use anything from performous and create
"libperformous".

2015-04-07 15:17 GMT+02:00 Daniel Schürmann <notifications@github.com>:

> Thank you for the quick responds.
>
> Yes the sound card solution will also work, but we still need to plug the
> mics for the Karaoke. We may use Jack. to get around it, but the Jack
> implementation offered by Portaudio is not suitable for such inter process
> routing.
>
> add ultrastar-txt support to mixxx
>
> Yes, this probably suits best for my case. But I am afraid it is hard to
> do from the scratch and to maintain this piece of code later.
>
> Will it possible to extract a lets say "libperformous" from your code base
> and reuse it in Mixxx? If Mixxx can provides somehow the track path, the
> seek position and the tempo, can this library then do the video rendering?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/performous/performous/issues/140#issuecomment-90546933>
> .
>



-- 
groetjes
niek nooijens

-----------------------------------------------
something's happening:
http://www.youtube.com/playlist?list=PL-tbXZUAoV4nFh7wi9avIY5eZbILiuOMu
<http://www.whylinuxisbetter.net>

**Comment by daschuer** [comment]
Good news. I have not dived into the Performous code, but I am afraid this approach will likely grow to a big size project. Not sure if it worth the work or of I should stick to the hardware solution. 

Do you have already a recipe in your head how this will work? Can you point me to the Performous code where I should start to read? What could be the architecture/data-flow of such an approach?

**Comment by nieknooijens** [comment]
take a look in song.cc/hh (where song data is stored) songs.cc/hh (a database of all the songs with search-function and auto-scan of folders) and the songparser files (which decode the ultrastar-txt files and store them in song classes) there's probably a simpler implementation in performous/composer since that doesn't handle the file scanning and such. drawing occurs in screen-sing.cc/hh and that's based on the data in song.cc/hh.

**Comment by daschuer** [comment]
Thank you!

**Comment by nieknooijens** [comment]
I think we can close this one due to inactivity
