### ISSUE TITLE
View time till song number X

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#182]
With the webserver now being included in master i'd like to have another feature for the webserver.
Currently you can show the playlist but can't see how long it takes till your song requested is being played.
So within the playlist it'd be nice to see how much time till song number x is going to be played.

Example:

```
0. ABBA - Dancing Queen << current song being played with 5:23 minutes left of time (this one doesn't need to be on the playlist)
1. ABBA - Waterloo 5:23 << time of current playing song (mm:ss) which will count down.
2. ABBA - Mamma Mia 8:10 << time of the current playing song + playtime from previous songs
3. ABBA - Super Trouper 10:07 << current playing song + time of previous 2 songs 
```

Et cetera.

By adding this you can tell people you have to wait for X minutes instead of guessing the time.
It would be nice to have all the time values be counting down as the current song passes by.

If i have time I'll look into this.

**Comment by nieknooijens** [comment]
this is a very often requested feature, unfortunately this isn't going to be an easy fix.
Basically we need to add a function to playlist.cc that checks the length of the songs.
You cannot use the notes for that since they're only loaded on play time so it needs to be extracted from the music file. the music file can be anything! ogg, mp3, wav, etc. currently we just dump the mp3 through libavcodec and it will provide us uncompressed audio, so I hope libavcodec has a way to get a songs duration.
for optimization I'd reccommend to store the duration in the song class so once it's extracted from the audio file it doesn't have to be checked again when it's still in the playlist.

**Comment by nieknooijens** [comment]
ok in theory this should work:
https://github.com/performous/performous/tree/PlaylistDuration
in practice it doesn't... what am I doing wrong? the filepath is correct...

**Comment by nieknooijens** [comment]
![schermafdruk van 2016-04-16 15-44-29](https://cloud.githubusercontent.com/assets/2794331/14581333/5cdb372e-03ea-11e6-9e38-2430afa40232.png)
good news! it's working, but when adding stuff to the playlist I need to decode the whole file to determine it's length, so it brings some lag, at this moment that's not a problem since it's loaded at the start of the playlist screen, and once it's loaded it's in memmory and can be accessed at any time but when you add this to the webserver interface we should make it load asynchroniously to avoid lockup on the main thread.

**Comment by nieknooijens** [comment]
just realized something:
webserver is already a different thread, I can just dump a mutex in the song object and it'll work!

**Comment by nieknooijens** [comment]
![schermafdruk van 2016-04-16 19-02-03](https://cloud.githubusercontent.com/assets/2794331/14582457/c062bf68-0405-11e6-916c-bc9afffbb21e.png)
it's now in the web interface too

**Comment by nieknooijens** [comment]
changes are now in master
