### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by hmvp** [performous/performous#184]
http://www.downforeveryoneorjustme.com/performous.org

**Comment by nieknooijens** [comment]
please report website related bugs here:
https://github.com/performous/web

**Comment by Baklap4** [comment]
I can't reach it from my mac. I can from my phone (wifi and 4g) and windows and linux.

**Comment by nieknooijens** [comment]
yeah I know, but I'm not in charge of the site, @TobiX is...

**Comment by TobiX** [comment]
No, I'm not. If I would be in charge, it wouldn't be down, because I would host it on GitHub pages, not on someone's home server... It's now "unreachable" since @Tronic activated HSTS, then his host went down and currently, @yoda-jm is hosting the site, but since he hasn't access to the SSL certificate, it's without SSL, which breaks the site for everybody who visited the SSL version at least once.

I'll close this issue for now, if there are new insights, please report a bug against the https://github.com/performous/web repository.
