### ISSUE TITLE
Requiring cmake 3.1?

### ISSUE THREAD

**Issue by TobiX** [performous/performous#237]
I'm currently in the process of doing some cleaning on the build system. We have currently very hacky C++11 support, I want to replace that with proper cmake C++11 detection. Unfortunately, that feature is only available since cmake 3.1, so I would like to require that version.

From what I see, this is no problem on Windows or OS X.

Of the supported Ubuntu releases, this only affects trusty (so this affects our CI setup on Semaphore) and I can build a PPA for that.

In two days (17.06.17), Debian stable meets that requirement.

Any objections?

**Comment by nieknooijens** [comment]
there already is a cmake version check, i suggest you use that to script in
the new cmake 3.1 stuff. this way we can keep backwards compabity for
another year or 2. after that it's safe to screw over those with ancient
versions ;)

Op 15 jun. 2017 19:12 schreef "Tobias Gruetzmacher" <
notifications@github.com>:

I'm currently in the process of doing some cleaning on the build system. We
have currently very hacky C++11 support, I want to replace that with proper
cmake C++11 detection. Unfortunately, that feature is only available since
cmake 3.1, so I would like to require that version.

From what I see, this is no problem on Windows or OS X.

Of the supported Ubuntu releases, this only affects trusty (so this affects
our CI setup on Semaphore) and I can build a PPA for that.

In two days (17.06.17), Debian stable meets that requirement.

Any objections?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/performous/performous/issues/237>, or mute the thread

**Comment by TobiX** [comment]
Well, that's a basic concept of cmake to declare the minimum version of cmake each script requires. I would have to raise that to 3.1 for the newer features I want to use...

**Comment by Tronic** [comment]
I've updated the project main level CMakeLists to use C++14ish (depending on which compiler is detected), which seems to be working (even with SemaphoreCI).

If this issue is still relevant, please clarify. Otherwise should be closed.
