### ISSUE TITLE
Webserver crash on start due to port already in use

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#299]
I also experienced a webserver crash in a couple of occasions. Now, note... this might not be an actual issue because the internet and even the wifi in here is particularly shitty. Nonetheless, we should be able to gracefully handle this instead of producing a crash.

[performous_2017-11-12-022201_Anasas copy.log](https://github.com/performous/performous/files/1464867/performous_2017-11-12-022201_Anasas.copy.log)
[performous_2017-11-12-022211_Anasas copy.log](https://github.com/performous/performous/files/1464872/performous_2017-11-12-022211_Anasas.copy.log)

**Comment by Baklap4** [comment]
The thing happening here is:
* Performous crashed somehow
* Restarting performous generates a new crash due to port being still used by crashed performous

# Solution 1
Stall webserver startup till port is freed by the kernel and showing the user a message webserver temporarily not available (for that time)

# Solution 2
Start webserver on random generated port (which might be free).

I think we should aim for solution 1.

**Comment by Lord-Kamina** [comment]
As discussed on Discord, I agree Solution 1 should be the goal.

**Comment by Baklap4** [comment]
Fixed submitted as per #318
