### ISSUE TITLE
Upgrade to latest cppnetlib Or use boost

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#306]
We should upgrade from cppnetlib 0.11.2 to the latest stable (0.12.0) 
Docs for 0.12.0 are to find here: http://cpp-netlib.org/0.12.0/index.html 

Or while at it completely remove the cppnetlib library since it's not supported anymore in ubuntu > 17.10
and drop back to use boost::asio (http://www.boost.org/doc/libs/1_65_1/doc/html/boost_asio/examples/cpp11_examples.html )

Personal favorite goes to drop cppnetlib and use `boost::asio` since we're already using lots of boost and it's still in the repo's.

Related issue: #288 

Vote :heart: (using `boost::asio`) vs :+1: (upgrading cppnetlib)

**Comment by Lord-Kamina** [comment]
I'm inclined to agree with dropping cpp-netlib.

**Comment by Baklap4** [comment]
@Lord-Kamina vote by emoji ;)

**Comment by nieknooijens** [comment]
@Baklap4 voted as well, cpp-netlib is dropped from official repo's, boost::asio however is very unlikely to be dropped.

**Comment by Baklap4** [comment]
First i'll fix the webserver issues, then i'll get up to this someday since it's an enhancement

**Comment by Baklap4** [comment]
THe webserver issues are fixed but still need some documentation.. almost done..

**Comment by Tronic** [comment]
Dropping the dependency would be nice but Boost.ASIO is way too low level. DIY request handling, URL encoding etc. seems like a very bad idea.

Possibly we could bundle Cpp-netlib with Performous and have it (statically) built as a part of Performous build? This avoids the dep and still gives us the benefit of using a HTTP library instead of bare-bones ASIO.
