### ISSUE TITLE
sound problems when rewinding songs twice

### ISSUE THREAD

**Issue by katsuowota** [performous/performous#33]
when rewinding a song twice really fast, the sound stops and the song continues, when playing a  bit around with the song again (forwarding, rewinding) the sound starts playing again.

**Comment by Baklap4** [comment]
How's this with the latest master after 4 years?

**Comment by Baklap4** [comment]
@Lord-Kamina you did some stuff with audio lately did you still encounter this bug?

**Comment by Lord-Kamina** [comment]
I've encountered this occasionally, yes.

**Comment by Tronic** [comment]
I would suggest changing ffmpeg.cc so that it seeks to correct location rather than to beginning of song if the requested time is (more than a fraction of a second) behind current timestamp or much ahead of current timestamp. Then test if audio still plays in sync with lyrics/notes/video after such rewinding (this was a problem a decade ago when I wrote the code). Feel free to hack (I have no time).

**Comment by OznOg** [comment]
I'm working on this problem, I think I may eventually endup with something; That said, I think could the PR 512 could be merged separatly as the rework for this is quite different, IMO
