### ISSUE TITLE
Coughing in my microphone causes segfault

### ISSUE THREAD

**Issue by MairusuPawa** [performous/performous#38]
Now that's one weird issue.

I mostly use, for now, Performous's "Training" feature (read the microphone's pitch and shows it on a sheet). This tool is useful to me when creating song files with Composer alongside, as seen as in a semi-related issue report on COmposer's GitHub page.

My microphone is actually a throat microphone. This allows me to keep my hands free while working, and minimize external noise impact. However, it tends to over-amplify some sounds, such as coughing , or scratching near the throat; in such cases, Performous tries to analyze the pitch and draw notes on screen, fails, and segfaults.

When launched in a Terminal, the error is reported as:
"terminate called without an active exception"

This might be a hint regarding how Performous handles the microphone inputs. I doubt this could appear in-game, in regular play situation - the input usually isn't that aggressive.

OS: Ubuntu 12.04 64bit
Performous 0.7.0

**Comment by Elandig** [comment]
I triggered a kernel panic by coughing near my motherboard, please fix.

Lock up the thread before redditors turns this thread into a shitstorm.

**Comment by Jpfonseca** [comment]
It's already on Twitter too.

**Comment by Zetelias** [comment]
Please help i scrolled too fast my BIOS corrupted :/

**Comment by Lord-Kamina** [comment]
> I triggered a kernel panic by coughing near my motherboard, please fix.
> 
> Lock up the thread before redditors turns this thread into a shitstorm.

We tried but the computer began playing a coughing sound on loop.

**Comment by gkkulik** [comment]
> I opened the link just fine without logging in without and with a VPN suggesting they don't even block possibilities of bots passing by, they instead just detect and login wall rude people, so it is a skill issue for you.
> 
> The comment is 100% relevant here as it is the source of the articles.

Source of what articles? What are you talking about? This is literally creating mess in a bug report. I can see though that your nick seems to origin from the place where the designated streets are so no wonder you can't grasp the idea of order.

**Comment by gkkulik** [comment]
@Lord-Kamina Okay, sorry.

**Comment by Earthcomputer** [comment]
Me trying not to sneeze why using performous

<img width="600" height="805" alt="Image" src="https://github.com/user-attachments/assets/79af9221-0b37-4ac6-ac99-43bae304796e" />

**Comment by ambhaiji** [comment]
@gkkulik I'm sorry some of my people are so busy in a loop of wondering if they may or may not be able to eat tomorrow they don't have surplus time to clean outside of their houses.

A place where any government officials who do care are not granted the budget to make progress, because they are not the place worth investing their budget towards. Be grateful you live in territory where the government more often than not gets shit done. 

If you actually bother to Travel to India or Pakistan one day you'll find that there are newer cities that are very clean. Some old cities that are musty and the outskirts that are a mess like every other country on this planet. Even high income places with strong government support like UAE, Saudi Arabia, Kuwait, Oman and Qatar have slums, they may not be as bad off as the others but every country has places with room for improvement. It is just that in a place of 1.4 billion people the number of people that need better quality of life and need help acheiving it is larger than the population of your whole country(most likely).
