### ISSUE TITLE
extend Audio equipment guide wiki page

### ISSUE THREAD

**Issue by jose1711** [performous/performous#430]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

[Audio equipment guide](https://github.com/performous/performous/wiki/Audio-equipment-guide) is a great source of useful information already but what it fails to mention completely is the viability of using
* Bluetooth speakers/microphones
  According to my tests (w/ a low-end bluetooth 3.0 speaker) bluetooth audio is totally unusable for karaoke due to latency issues. Many forum posts found on the internet (dedicated to buyes of bluetooth audio sytems) seem to confirm the problem and add this is a hw limitation of Bluetooth. But who knows.. maybe BLE is different (better)?

* Wireless mics
  Presumably no miracles should be expected from systems like this: https://www.aliexpress.com/item/EYK-E100-Long-Range-UHF-2-Channel-Wireless-System-Dual-Handheld-Microphone-Mic-Clean-Sound-for/32906492214.html but I do wonder whether anyone has any real experience with it. And also if it suffers from any lag (out-of-sync) problems. And maybe some actual tips for wireless mics too.

* Karaoke session shared over Internet

  Not 100 % sure this would belong here so maybe it'd deserve a separate page. I wonder if setup as conference call sharing Performous screen + e. g. a [Jamulus](http://llcon.sourceforge.net/) for a over-the-air karaoke session has been tested by anyone and if it's even worth playing with.

**Comment by nieknooijens** [comment]
wireless mics can indeed be placed under the audio equipment guide. general rule is: use professional or "prosumer" grade stuff. I have an STWM712 wireless mic set which works fine... as long as you are the only one using it, since you can't change the frequency. also some older 800MHz models are going to get busted because of 5G cellular networks. 
Other than frequency issues, anything VHF or UHF should work fine.

**Comment by jose1711** [comment]
a few updates to audio guide have been done. closing.
