### ISSUE TITLE
Error compiling webcam

### ISSUE THREAD

**Issue by deuteragenie** [performous/performous#466]
See issue https://github.com/performous/performous/issues/429

Trying to compile on Raspbian Stretch: the same issue still exist on master. 
Debian Stretch defaults to OpenCV v2.4.9 I think.

Is there a recommended version for OpenCV ? I see that 3.2.0 is available for Debian.

Workaround: compile without WebCam support.

**Comment by Baklap4** [comment]
Within our build system we're using the following versions
OSX (10.14.6) 3.4.8
Ubuntu (18.04) 3.2.0
Ubuntu (16.04) 3.2.0

These are all working versions since we always build them with all options enabled in the CI.

With windows we're using 3.4.7 if i'm correct.
In windows i can see there is opencv 4 available (4.1.1) so i might be able to test that once #507 is merged
