### ISSUE TITLE
Requiring signature on commits. 

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#498]
@performous/core-owners @performous/contributors 

Everybody who commits here, I'd like your opinion on this. I'm for (and think we should enforce) GPG-signed commits.

Anybody disagrees or has a different take?

**Comment by Tronic** [comment]
To be blunt: I believe that PGP and other 20+ year old crypto technology should be removed from earth, and that signatures in general seem just dead weight on top of the authenticity verification that Git itself implements. It's not something that I'd ever use (anymore), and especially not on a game project.

**Comment by Baklap4** [comment]
Signed commits would only be necessairy for merges to master imho. This will deffo take the 'clone the repo and do stuff and create a pr' more of a hassle for most git endusers i think; resulting in less pr's (we already have not many)

**Comment by Lord-Kamina** [comment]
Sounds like a ressonable compromise to me.

**Comment by Tronic** [comment]
Since I am no longer a core developer of Performous, that would not affect me, but to elaborate: PGP is broken in that it provides no (usable) mechanism for key renewal, exchange and verification.

You create a key pair once and never change that, and the only security that this provides is mild confirmation of a new commit being signed by the same user as the previous ones. That is, unless that developer's keys *ever* get hacked or otherwise handed to third parties, like the police, which has happened to me. I doubt that anyone would actually use strong enough passwords to protect their keys, especially since the password KDF is very weak (medium length passwords are easily brute-forced).

People often lose their keys (broken hard drives and other such incidents), so in practice anyone creating a keys for themselves would not really rise eyebrows, thus eradicating the only security that this system could provide in the first place (i.e. there is no telling if it actually was someone else *pretending to be the original developer* having lost his keys).

The signature hash AFAIK still defaults to SHA-1 which is known to be broken (also affects Git). Further, RSA is still dominant. Although better hash functions and elliptic curve support have been added to OpenPGP, I don't see anyone using them. RSA is quite insecure, requiring huge 4096 bit keys.

In Git context such verification is also quite moot because anyone can easily verify what was changed and whether that matches their local history. If we take that Github itself is trusted (despite being owned by Microsoft), all PRs and merges are inherently tied to known user accounts.

There are also modern alternatives for secure signatures, if you find some use for them in this context:
https://blog.gtank.cc/modern-alternatives-to-pgp/ (minisign/signify seems like a reasonable option and is already used in the OpenBSD project for signing commits).

**Comment by Baklap4** [comment]
@Lord-Kamina do you have an answer for your question? If so I think this can be closed.

**Comment by xurizaemon** [comment]
Previously #409 also

**Comment by Tronic** [comment]
@xurizaemon Hmm, so enabled for three years but apparently never used? I wish Github would implement modern signatures because they still only support PGP. Signing not commits nor PR merges but releases would at least make some sense. This of course only if the signing key is kept offline or on a security device, such that a hacker cannot get immediate access to the key at the same time he gains access to push stuff to Github by hacking some developer/admin of the project. Minisign still looks like the best option.

**Comment by xurizaemon** [comment]
I actually didn't check if anyone was using the feature - just noticed two apparently related issues that didn't mention each other while browsing the queue of a project I had just started using, while looking for a fix for another unrelated issue I thought I was seeing.

Performous is great, thanks team!
