### ISSUE TITLE
FFT and pitch detection going forward.

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#528]
Currently, we calculate pitch and fft while singing using in-house code based on aubio and the libda headers.

Considering we've recently integrated aubio (and therefore fftw-3), maybe it'd be worth looking into switching to doing it with the aforementioned libraries?

**Comment by Tronic** [comment]
I believe that Performous' own pitch detection is the best algorithm that is freely available. A couple of companies have commercially licensed it from me for their products because they didn't find anything better. Certainly there is room for improvement but AFAIK other open source solutions are either very basic FFT or autocorrelation based. Let me know if you find a better one.

One interesting approach I've been pondering is using convolutional neural networks to analyse the FFT output (after mild post processing like frequency correction). This might lead to more reliable detection but could also allow differentiating tonal qualities (humming, vocal singing etc), but for training a good set of sample recordings would be needed. Also, there is an algorithm that used to be patented but that is probably already expired about the FFT itself, calculating it only for one full cycle at each bin (instead of full 1024 samples in each bin), reducing latency on higher frequencies.

**Comment by Tronic** [comment]
Re: the C++ template-based FFT: We used fftw3 earlier but switched the the C++ implementation because it was easier to use (no init calls to precalc because compiler does it, just a single function call where needed), and this was also benchmarked at the time to be actually faster than fftw3 at size 1024 (probably due to inlining compiler optimizations, only possible with templated solution).
