### ISSUE TITLE
Can't start in Raspberry Pi 4: Couldn't find current GLX or EGL context

### ISSUE THREAD

**Issue by Dikakus** [performous/performous#561]
### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I downloaded performous from Raspbian respositories and tried to launch.

### What did you expect to see?
Performous running.

### What did you see instead?
An error message.

### Output of `performous --version`: (_What version of Performous are you using?_)
```
Performous 1.1+
```

### What is your environment & configuration (arguments, platform, ...)?
Linux raspberrypi 4.19.118-v7l+

I ran the program as:

performous -l debug --audio "dev=0"

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
audio/debug: Will try to find device matching dev: 0
audio/info: Found: C-Media USB Audio Device: - (hw:2,0), in: 1, out: 2
audio/error: Audio device 'dev=0': Pa_OpenStream failed: Invalid device
core/info: Loading assets.
video/info: Create window 1366x768
stderr/info: performous: ../src/dispatch_common.c:863: epoxy_get_proc_address: Assertion `0 && "Couldn't find current GLX or EGL context.\n"' failed.
Abortado

Complete log in attached file.
```

[infolog.txt](https://github.com/performous/performous/files/4873568/infolog.txt)

**Comment by Lord-Kamina** [comment]
This is something to be improved but not a bug. Performous does not currently support OpenGL ES.

**Comment by Lord-Kamina** [comment]
To elaborate, the current requirement for full OpenGL is 3.3 core profile, which according to https://www.raspberrypi.org/blog/vc4-and-v3d-opengl-drivers-for-raspberry-pi-an-update/ is not supported.

The solution is to make performous compatible with OpenGL ES, which is almost certainly possible  but we're spread thin as it is and haven't made a release in over 4 years, so it's not something we're likely to tackle soon because it's most likely going to be a fairly big task.

**Comment by deuteragenie** [comment]
I did a bit of research on support for GLES a while ago...
If I remember well, the SDL context should be created for GLES instead of GL and...
shaders should be declared with #version 310 ES or similar instead of #version 330 core
I think I recompile most/all shaders at the time and they were fine, but one (can't remember which unfortunately).

**Comment by Tronic** [comment]
Pull requests are welcome.
