### ISSUE TITLE
add support for more audio formats

### ISSUE THREAD

**Issue by JohnSmith2007** [performous/performous#687]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Add support for more audio formats other than MP3 (better formats like WAV, OGG, etc.)
Because I'm getting tired of having to convert my Rock Band stems to MP3 to get 'em to work.

**Comment by Baklap4** [comment]
If i'm correct we support other formats than mp3
Music -> mp3|ogg|aac
Video -> avi|mpg|mpeg|flv|mov|mp4|mkv|m4v
Images -> png|jpeg|jpg|svg
Midi -> mid

see: https://github.com/performous/performous/blob/f3c58ba4275b35a7c0bc097175f987d93fc8c301/game/songparser.cc#L116-L133

![image](https://user-images.githubusercontent.com/3918517/134866375-cef43a49-0a5b-4208-ae2d-4737ec90a88d.png)

Closing this since we do support "one of the better formats". Please reopen this if you think this is currently not working
