### ISSUE TITLE
Implement rap notes support

### ISSUE THREAD

**Issue by MairusuPawa** [performous/performous#692]
Hello! This is related to the karaoke part of Performous.

Some time ago (when?), Ultrastar and some derivatives started to introduce the concept of "rap" and "golden rap" notes. Some files have started including these, but unfortunately, they make Performous crash.

In Ultrastar, freestyle notes don't give points to the singer. Rap notes in USDX don't work the same as in Singstar - they allow you to score points when some sound is detected in the microphone, whatever the pitch is. They actually work the same as Freestyle notes in Performous currently. Golden rap notes work the same, but contribute to the golden notes score.

In a .txt file, rap notes are denoted as follow: "R", length, pitch, lyrics

```
- 2687
R 2689 2 0 It's
R 2692 2 0  not
R 2696 3 0  the
R 2700 3 0  per
R 2704 3 0 fect
R 2708 3 0  so
R 2712 3 0 lu
R 2716 1 0 tion
- 2718
```

Golden rap notes are the same, but the lines start with a "G" instead of "R".

I'm not sure how the feature could be implemented in Performous, but it would be great if the game didn't crash when loading such a song at least :)

**Comment by TobiasKe** [comment]
Hello,

If I see it correctly, this was actually already implemented in [pullrequest #568 ](https://github.com/performous/performous/pull/568).
From the code, the Notes should behave as follows:
'R' notes are currently treated same as Freestyle 'F' notes
'G' notes are currently treated same as normal golden notes, so you need to hit the correct pitch.

Since the pullrequest is from september 2020, the support for these types of notes should be working in current versions of Performous. The offocial release, however, is from before that date.
I did a quick test, to verify this:
On my custom compilation from mid last year, I couldn't reproduce the problem. Performous shows the notes as described above.
However, on my Performous 1.1 installation (still the most recent official release), performous refuses to play a test song that contained  'R' and 'G' notes. It doesn't crash; it simply refuses to play the song due to unknown note types.

So if you need the support for 'G' and 'R', you could try the current [pre-release](https://github.com/performous/performous/releases/tag/1.2.0-rc1). Otherwise you probably have to wait for the next official release.

Still, one could discuss how golden Rap-Notes should be treated, since they're currently simple golden notes.

Best regards
Tobias
