### ISSUE TITLE
Future automation plans

### ISSUE THREAD

**Issue by ooshlablu** [performous/performous#707]
## Improve Existing Automation
- [x] Migrate [performous-docker](https://github.com/ooshlablu/performous-docker) to the Performous org
- [x] Migrate [ooshlablu/performous-build](https://hub.docker.com/r/ooshlablu/performous-build) to / create Performous org in Docker
- [ ] Set up rules for PRs and merging based upon Performous repo
- [x] Rework https://github.com/performous/performous/pull/635 (Replaced by https://github.com/performous/performous/pull/708)
- [x] Figure out semaphore's way of producing artifacts for build and push existing Linux packages to there

## Future improvements
- [x] Investigate current OS build situation for Semaphore (Especially Windows)
- [x] If Windows not supported on Semaphore, Investigate github actions
- [x] When either platform is fully supported, build packages for all supported OS's and publish them each release

## Decisions that need to be made
- What does a ""release"" mean?
  - Do we only want to release on tags?
  - What will be the materials/assets produced for a release vs a standard build or dev build?
    - Should we produce packages for _every_ build, including PR's? (I personally vote yes for this as it will give higher confidence in and ease testing of each PR)
  - Do releases require more sign-off than any standard build?
- Should the performous/deps repo be public?

**Comment by Baklap4** [comment]
> Set up rules for PRs and merging based upon Performous repo

PR's -> Build + create packages to see if it still works
Merge to master -> Build + deploy as 'latest'
Nightly build on master -> Build + deploy as 'nightly'
Upon tag -> Build + deploy new release

Aside from these CI/CD rules we might wanna look into style-checking, vulnerabilities, dependency scanning, etc. I thought @OznOg did a try-out with a tool for static analysis?

> Figure out semaphore's way of producing artifacts for build and push existing Linux packages to there

Semaphore's artifact system sucks ass. The artifacts can only be downloaded if authorized which the majority won't be. We could take a look into pushing artefacts to our website, but Github Pages only allows 1GB of website data. This should be sufficient enough to host the latest/nightly build. See performous/web how to make a commit on that repo

> Investigate current OS build situation for Semaphore (Especially Windows)

I've asked semaphore about 2 years ago if they were going to support Windows. Up until now they still don't support it and it's still in unknown when it actually will go live. See ticket: https://github.com/semaphoreci/docs/issues/741

> If Windows not supported on Semaphore, Investigate github actions

This is our best bet, in fact i think it'd be best for us to completely move over to github actions as it gives us way more freedom in things we want to do: saving artifacts, docker builds, window builds, static analysis, dependency checking, vulnerability scanning etc + it's in the Github ecosystem.

> What does a "release" mean

In my opinion a merge to master should be releaseable. And thus every merge could potentional be a release. This is where the nightly build and/or latest build can come in handy.

The better question to ask here is when to ship a release.

This is what the wiki has to say about it: https://github.com/performous/performous/wiki/Release-process but feel free to discuss it here.

> What will be the materials/assets produced for a release vs a standard build or dev build

For local development just run a standard build in Debug mode.
A build from the CI/CD should always be in Release mode, preferable matching an actual release.

> Should we produce packages for every build, including PR's? (I personally vote yes for this as it will give higher confidence in and ease testing of each PR)

I'd vote for yes, since it gives us a higher confidence that things didn't break and we always test the 'deploy of a package' and see it doesn't break with the new or altered code. A bonuspoint would be that the artefacts gets attached to the PR so people can just download the binaries and test it without having to build the system. This will increase help from our testers who might not have a development setup ready to go.

Comenting on _every_ build.. we currently have a gcc, clang and meson build. The meson build state is currently broken. It was added as a try-out and i think it's time we say either keep supporting it or removing it. With the Windows build added to the CI/CD we also have msvc coming as a 3rd compiler. Also what is the reason we have both gcc and clang? Both will work in any situation yet now we have to please both compilers in terms of warnings / build-flags. If there's no real reason we might be able to scrap either gcc or clang.

> Do releases require more sign-off than any standard build?

What do you mean with Sign-off? Currently (but not enforced) we need to have a go from all core-developers to make a release. I think this can stay and be managed in a dedicated channel on discord (#release_draft)

> Should the performous/deps repo be public?

I don't see the harm in having it public. On the otherhand those repo's are tailored towards us and other people shouldn't fork them for any other work besides performous.

Aside from the points mentioned above it was also mentioned to add git-precommit-hooks to check for simple indentation/style issues. Also check #514 
All the tools we want should be available from within the CI/CD and should be run on every PR/Merge to master.

Then at last within this project there are 0 unittests. It'd be nice to create them (and run them in the CI/CD) however the way Performous is coded as of right requires lots of hacking to make some nice unit tests. Cmake supports executing a test-runner, but maybe @OznOg or @Lord-Kamina have a better system for this?

**Comment by ooshlablu** [comment]
> Comenting on _every_ build.. we currently have a gcc, clang and meson build. The meson build state is currently broken. It was added as a try-out and i think it's time we say either keep supporting it or removing it. With the Windows build added to the CI/CD we also have msvc coming as a 3rd compiler. Also what is the reason we have both gcc and clang? Both will work in any situation yet now we have to please both compilers in terms of warnings / build-flags. If there's no real reason we might be able to scrap either gcc or clang.

Ah, so, I think we should change the definition of "build" in regards to compilers. IMO, it should be "native" per OS, ie. linux builds should be `gcc`, MacOS should be `clang`, and Windows should be `msvc`. So therefore, each time there's a PR or tag or whatever, it gets built with all 3 compilers because it would be running on all of those OS's.

**Comment by ooshlablu** [comment]
Ok, I believe my questions have been answered sufficiently, and my mission is clear. I mentioned this in chat the other day, but keeping it here for clarity:
- Move Ci/CD to GH Actions
-  Produce "Release" Packages (native per platform) for each PR, merge to master, and tag
- Retire Semaphore

@Baklap4 I will need your help with the Windows build since I'm allergic to OS's that aren't Unix or Unix-like :-)
Will hit you up when I get there

**Comment by Baklap4** [comment]
> @Baklap4 I will need your help with the Windows build since I'm allergic to OS's that aren't Unix or Unix-like :-)
Will hit you up when I get there

If you have the actions up and running hit me up. I think it should be pretty easy to set up :)

**Comment by Baklap4** [comment]
> [@ooshlablu ].... but i made some good progress
https://github.com/ooshlablu/performous/blob/github-actions/.github/workflows/build_and_release.yml
https://github.com/ooshlablu/performous/releases/tag/untagged-d99b97b08648274b1f82
https://github.com/ooshlablu/performous/actions/runs/2093900883

@ooshlablu The workflows you have so far are looking good!

As said on discord i wanted to comment about releases.
Like said above every pr, merge to master and tag should be releaseable.
A strategy we use in our company is when we create a PR an automated release is build in the form of `<major>.<minor>.<patch>-alpha-<PRnumber>-<shacommithash>`. This release isn't published as a tag or shown on the github releases pages. but merely as artefacts attached to the PR.

Then whenever we merge a PR to master we create an automated beta release in the form of `<major>.<minor>.<patch>-beta-<buildnumber>-<shacommithash>`. It'd be nice to add some info to the readme about our latest beta release. The buildnumber is needed since shacommithashes aren't persé sorted correctly. With an increasing buildnumber every next version is correctly and logically shown

After some time of testing we say it's ready to become an official release so we create the tag `<major>.<minor>.<patch>` upon which the pipeline triggers and an official release is made.

For performous i think it'd be wise to use the same principle but with 'release-candidates' in between as a final form of testing.
A release candidate is posted as an official pre-release and also listed as such. This rc gets a tag and a branch dedicated to it. And after the pipeline is done the summary of the pre-release can be made and then be published with the automaticly attached binaries.

In regard of the version changes, this can become an action the developer has to do **and** include within his PR. However this can become problematic and quickly increases our versions.. so i think _for now, untill we have a better solution_ the version bumps will be a manual process.
