### ISSUE TITLE
Trying to change sort criteria in screen_songs kicks you to main menu

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#774]
### Performous & operating system versions

Performous: 1.2.0
Operating System: macOS 11.6.6

### What is the problem?

Sorting can't be changed

### Steps to reproduce

Go into the song selection screen and try to change the sort ordering.

### Additional context

Using git bisect, I've traced the issue to 5ca3d79b6e5273e98201669092b093d509eb344d, but I have no idea what change in that commit could be responsible for this.

**Comment by Baklap4** [comment]
It's because of these lines: https://github.com/performous/performous/commit/5ca3d79b6e5273e98201669092b093d509eb344d#diff-9e4a0f5276f1a8558ac891c338bdd361b44032c9e3ac664c95e9330276d1bd4eR333-R340

I just don't get why the language is changed upon changing the sort order

relevant log section:
```
songs/notice: Done Loading. Loaded 4 Songs.           
songs/notice: Done Caching. << this was before changing sort order. The rest below is after changing sort order.                        
Wanting to change something, old value: 'Dutch' new value: 'Auto'                                                
locale/notice: Setting language to: 'Auto'                                                                       
locale/notice: Current language is: 'Auto'                                                                       
Saved configuration to "C:\\Users\\Arjan\\AppData\\Roaming\\performous\\config.xml"                                     
ffmpeg/warning: Negative audio sample_position -276 seconds, frame ignored.
```

This is also still happening in the latest master.

Another note: changing the: Type sorting doesn't do this
