### ISSUE TITLE
Windows builds missing webserver.

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#793]
### Performous & operating system versions

Performous: master
Operating system: windows

### What is the problem?

CI builds are being explicitly built without webserver, even though we're installing cpprestsdk.

### Steps to reproduce

Not needed

**Comment by Baklap4** [comment]
previously opened but now closed pr: https://github.com/performous/performous/pull/712

it worked at that point in time. But then it was decided to not get this merged since there was already work done with restinio (@Lord-Kamina ) vs httplib (@yoda-jm ) which i still think is the better option. Therefore making this issue + the closed pr obsolete.

Personally i would close this as the release notes of 1.2.0 clearly state that the windows build does **not** contain the webserver

**Comment by Baklap4** [comment]
Closing this as per discussed on discord.
The reason #712 didn't get merged was already mentioned above, and we intend to either use restinio or http-lib at some point in the near future.
Also the release notes clearly state that the Webserver is not active on the Windows build 1.2.0.

If you want a windows build for download. It can be found attached to #712
