### ISSUE TITLE
[Design] Official Performous Avatars 2024 (Repo-Transfer)

### ISSUE THREAD

**Issue by marwin89** [performous/performous#928]
### Suggestion

- I made a special avatar collection for performous in co-op with @Baklap4 and @twollgam (total safe legally, see license.md)  
- Please transfer my repository into performous organisation 🚀 
- Repository is: https://github.com/marwin89/performous-avatars-official 🎨

### Use case

- As an official avatar collection for performous, this repository should be found (by devs and users) under performous organization 

### Extra info/examples/attachments

The question of avatars came up in
- "add Player management screen" PR #757 
- and #920 

Updates once a year

Preview
![performous-avatars-2024-official-preview](https://github.com/performous/performous/assets/63517874/a83c993c-62c5-440a-be23-702bc5d4940f)

**Comment by Baklap4** [comment]
@marwin89 thanks for the awesome avatar collection!
I saw some mockups which we can maybe incorperate into the #757 so that's quite nice! Not sure if we're going for mouse support within performous as asked in there but we'll see how this goes 👍 

For now i'll add you to our contributors team this way you'll unlock a couple of extra things within our repository 👍  But i'm not sure if you can then transfer the repository into the performous organization. If not, you'll have to invite me to your project so i can transfer it over into the organization 👍 

@twollgam @Lord-Kamina What you think of these avatars?

**Comment by twollgam** [comment]
@Baklap4 mouse support? Yes please, but please not in #757 ;-)

**Comment by marwin89** [comment]
> And the avatars should be come with https://github.com/performous/performous/pull/757 but the layout not. The layout needs much new code and I would like to make it themeable.

I agree let's do the next steps in player config layout in another ticket 👍 I'll open a new Issue. @twollgam thanks again! #757 is a goood progress and the foundation for further dev!

**Comment by marwin89** [comment]
@Baklap4 : thats the new Issue with the mockups:
- #931
